# ~/.ssh/ssh_config.d/ctrl.conf

# Unix supports ctrl socket paths
#    NT does not
Match tagged linux
  ControlMaster auto
  ControlPath ~/.ssh/ctrl/%r@%h_%p
  ControlPersist yes

# Control paths do not work on windows
#    NT does allow "auto", though this is not believed to produce any result
Match tagged windows
  ControlMaster auto
  ControlPath auto
  ControlPersist yes