# ~/.ssh/ssh_config.d/ctrl.conf

# Unix supports ctrl socket paths
#    NT does not
# Control paths do not work on windows

Match exec "dir /dev/null 2>$null 1>$null"
  ControlMaster yes
  ControlPath ~/.ssh/ctrl/%r@%h_%p
  ControlPersist yes

Match exec "dir c:/pagefile.sys 2>$null 1>$null"
  ControlMaster no
