# ~/.ssh/ssh_config.d/git.conf

Match host="github.com,gitlab.com"
  IdentitiesOnly yes
  IdentityFile ~/.ssh/keys/git
  IdentityFile ~/.ssh/keys/git_ed25519
  PreferredAuthentications publickey
  ServerAliveCountMax 3
  ServerAliveInterval 5
  User git

Include ssh_config.d/restricted/git.conf