
# Example of  ~/.ssh/ssh_config.d/restricted/infra.conf
#
# Match host="kvm-0,kvm-0.local,kvm-0.example.com"
#   HostName kvm-0
#   User root
#   IdentityFile ~/.ssh/keys/admin

Include ssh_config.d/restricted/infra.conf