# ~/.ssh/ssh_config.d/jump.conf

# Example of  ~/.ssh/ssh_config.d/restricted/jump.conf
# Match host="jumpbox"
#   HostName jumpbox
#   Tag jump
#
# Match tagged !jump
#   ProxyJump jump


Match final
  Include ssh_config.d/restricted/jump.conf

Match tagged=jump
  ConnectionAttempts 9
  ConnectTimeout 15
  ForwardAgent yes
  SetEnv __PROXYJUMP_GATE__=1

Match tagged=!jump
  SetEnv __PROXYJUMP_GATE__=0
  #SetEnv __PROXYJUMP_HOST__=
