# ~/.ssh/ssh_config.d/jump.conf

# Example of  ~/.ssh/ssh_config.d/restricted/jump.conf
# Match host="jumphost"
#   HostName jumphost
#   Tag jump

Include ssh_config.d/restricted/jump.conf

Match final
  Include cache/session_%C.conf

# NOTE: '%j' token added in openssh 9.6
Match final
  LocalCommand python "%d/.ssh/scripts/state_helper.py" "%n" "%h" "%C" "%L" "%j"
  ProxyCommand python "~/.ssh/scripts/session_ctl.py" "proxy" "%n" "%h" "%p" "%r"

Match tagged="jump" final
  ConnectionAttempts 9
  ConnectTimeout 15
  ForwardAgent yes
  LogLevel ERROR
  ProxyJump none
