# ~/.ssh/ssh_config.d/personal.conf

# Example of  ~/.ssh/ssh_config.d/restricted/personal.conf
# Match "all"
#  CanonicalDomains example.com-
#
# Match host="personal_computer,personal_computer.vpn.local"
#  hostname personal_computer

Include ssh_config.d/restricted/personal.conf